### ISSUE TITLE
Incompatibility Error with memoizee@0.4.16 and Node.js 21.7.3

### ISSUE THREAD

**Issue by hamzaelmaghari** [sequelize/cli#1503]
#### Description
During the installation or usage of `sequelize-cli`, an incompatibility error arises due to the required dependency on `memoizee@0.4.16`. The error message encountered is:

````
error memoizee@0.4.16: The engine "node" is incompatible with this module. Expected version ">=.0.12". Got "21.7.3"
````

#### Steps to Reproduce
1. Set up a Node.js environment with version 21.7.3.
2. Attempt to install or use `sequelize-cli`.
3. Observe the error message related to the incompatibility with `memoizee`.

#### Expected Behavior
`sequelize-cli` should install successfully, considering its dependencies, or there should be clarity in the documentation about the compatibility requirements with Node.js versions.

#### Actual Behavior
The installation or usage of `sequelize-cli` fails with the error message indicating incompatibility with the installed Node.js version (21.7.3), which is required by `memoizee@0.4.16`.

#### Environment
- **Node.js Version:** 21.7.3
- **sequelize-cli Version:** [Specify version if applicable]
- **Operating System:** [Specify]

**Comment by bipinmishra97** [comment]
I also faced the same issue, while executing the `yarn install` command with a different Node version **(20.10.0)** and `sequelize-cli` version **(6.6.2)**

```
error memoizee@0.4.16: The engine "node" is incompatible with this module. Expected version ">=.0.12". Got "20.10.0"
error Found incompatible module.
```

It seems that **memoizee** is being pulled in as a dependency of **cli-color**, which is in turn a dependency of
**sequelize-cli**.  I got this inner dependency from the below command
```
yarn why memoizee
```

It works fine if we do the yarn installation, ignoring the engine compatibility with the below command.
```
yarn install --ignore-engines
```

But, this is **not a proper solution.** Because it will also ignore other package's engine compatibility checks.

Please post if anyone has a proper solution.

**Comment by WikiRik** [comment]
[memoizee](https://github.com/medikoo/memoizee) is releasing 0.4.17 right now which will resolve this issue
