### ISSUE TITLE
Migration and promises 

### ISSUE THREAD

**Issue by etiennegauthier** [sequelize/cli#206]
Hello

I hope this is not a "learn nodeJS first" case in which case I apologize in advance (I'm a newbie in node).

I'm playing with migration in promise style and have noticed something very strange.

The migration code below will fail, the SQL command runs ok but the migration fails so it's all messy (with the metadata table out of sync): 
    down: function(migration, DataTypes, done) {
      migration.removeColumn('MyTable', 'MyColumn')
          .then(done);
    }

While the following will work fine:
    down: function(migration, DataTypes, done) {
      migration.removeColumn('channel', 'vicc_file')
          .then(function(){
          })
          .then(done);
    }

It only happens when I have 1 command to run. 
Am I doing something wrong ?

**Comment by sdepold** [comment]
Hi @etiennegauthier.

Please learn NodeJS first. :D 

...

Just kidding :)

The reason why you experience the weird behavior is because you are mixing promises and callbacks in migrations. If you do use promise style you can just return your promise from the migration and remove the `done` callback. This is how it should look like:

```
down: function(migration, DataTypes) {
  return migration.removeColumn('MyTable', 'MyColumn');
}
```

The reason why it wasn't working with the first version is, that `removeColumn` eventually resolves a value which is passed to the done callback as a first parameter. If the `done` callback is called with a first parameter other than null or undefined, it is treated as erroneous. Using the second version makes the promise resolve no value, which means the done callback is called without a parameter.

Does this help?

**Comment by etiennegauthier** [comment]
It helps a lot, thank you very much :)

**Comment by sdepold** [comment]
great :)
