### ISSUE TITLE
Make build matrix smaller

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/cli#348]
Currently we build on 2 js2coffee versions x 2 dialects x 3 sequelize versions x 2 node versions (0.10 and 4) = 24 jobs per build. I think we should not test against different js2coffee versions (coffeescript is dead anyway, we might even consider removing support entirely), build only against sequelize 3 and 4, and node 4 and 6 (= 4 jobs). Do we actually need to test different dialects? Isn't the cross-dialect support covered by sequelize?

**Comment by sdepold** [comment]
Hey @felixfbecker,

I originally tried to be compatible with every major version of sequelize but I'm fine with dropping some of the versions. Regarding CS: I added this functionality a not so long while ago because someone requested it. But again: I'm fine if we only support a specific version of js2coffee. By now I'd also say that node 4 and 6 should be fine. I tend to agree that cross-dialect can be considered given although I were running into problems with sqlite in the past. But again: Given the fact that sequelize should take care of the cross-dialect support, we can probably drop it and fix things if needed.
