### ISSUE TITLE
[MSSQL] yarn sequelize db:migrate ERROR: Login failed for user ''.

### ISSUE THREAD

**Issue by vaibhav6233m** [sequelize/cli#766]
## What are you doing?

I am trying to connect to SQL server using the following configuration for NodeJs API development as instructed  [here](https://github.com/talyssonoc/node-api-boilerplate#quick-start) 

```js
  development: {
    username: 'xxx',
    userName: 'xxx',
    user: 'xxx',
    password: 'xxx',
    database: 'xxx',
    host: '127.0.0.1',
    dialect: 'mssql',
    port: 1433,
  },
```

```bash
yarn sequelize db:migrate
```

## What do you expect to happen?
It should connect to the SQL server successfully based on the configuration provided. (able to connect from sqlcmd on the terminal without any issue)
It is getting connected to MySQL with similar configuration successfully.
The problem only seems to be with MSSQL.
I think the [username], [user] or [userName] keys are not matching with the config object to sequelize. 

## What is actually happening?

```bash
yarn sequelize db:migrate
yarn run v1.10.1
$ cross-env NODE_PATH=. sequelize db:migrate

Sequelize CLI [Node: 11.8.0, CLI: 3.2.0, ORM: 3.34.0]

Loaded configuration file "config/database.js".
Using environment "development".

ERROR: Login failed for user ''.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Developer Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS)

__Dialect:__ mssql 
__Dialect version:__ Tedious version 6.1.0
__Database version:__ 14.0.3076.1 (X64) 
__Sequelize version:__ 3.34.0
__Tested with latest release:__ Yes 3.34.0

**Comment by archae0pteryx** [comment]
I have the same issue.

**Comment by asdfjackal** [comment]
Gonna bump this. I am having the exact same problem but for me I also can't connect through regular old sequelize.

**Comment by stormmuller** [comment]
Yep we're having a similar issue, login works with using SSMS. 

We're using mssql and npm. this worked pre version 5.

**Comment by vipulpatel1994** [comment]
More for older versions:
If you are using sequelize@4, then it seems there is a hidden requirement that you must use tedious@<=5.

Which version of Sequelize are you using? If it's v5, According to Sequelize v5's document:

Sequelize now works with tedious >= 6.0.0

However, in its package.json, it does not depend on tedious at all. Since your program still runs, I guess you manually installed an older version of tedious before, which caused this strange problem.

Manually installing tedious of version>=6 should solve this problem, just like stated in its Getting started document page:

You'll also have to manually install the driver for your database of choice:
# One of the following: $ npm install --save pg pg-hstore # Postgres $ npm install --save mysql2 $ npm install --save mariadb $ npm install --save sqlite3 $ npm install --save tedious # Microsoft SQL Server

src: https://www.oipapio.com/question-3952323
