### ISSUE TITLE
Why is internet needed to run migration

### ISSUE THREAD

**Issue by adityagoel19** [sequelize/cli#803]
Hi,

I was deploying my code inside my client's VM which had all outbound blocked. So, I installed all my node modules including "sequelize cli" into my container before deploying the docker image on to my client. However after deploying docker and trying to run migration in the client's server didn't work and kept waiting on "npm session <some alphanumeric string>".

command I run - npx sequelize-cli db:migrate

**Comment by adityagoel19** [comment]
Anyone here?

**Comment by eseliger** [comment]
Check if the cli is resolvable from your working directory
npm ls sequelize-cli

**Comment by mattrunyon** [comment]
I think the problem is related to the name of the binary installed by the package.

npx initially checks for a local binary to run and if it can't find it, checks the npm registry for a package by that name. The binary that's installed is actually called just sequelize. If you check node_modules/.bin you'll see a symlinked sequelize to the sequelize-cli folder

I just ran into this the other day so I haven't had a chance to submit a PR for it (I also haven't ever messed w/ publishing npm packages). The fix should be to change the package.json to call the binary sequelize-cli instead of sequelize.

In the mean time, I have just been calling `npx sequelize db:migrate` which has been working without downloading the package from npm every time.

**Comment by adityagoel19** [comment]
Thanks @mattrunyon, I will check it out and let you know.
