### ISSUE TITLE
[QUESTION] Execute cmd functions from js code

### ISSUE THREAD

**Issue by xXLokerXx** [sequelize/cli#855]
Hi everyone i have this question.
I'm developing a program that could execute the migrations from other projects:
i'm using the comand `sequelize db:migrate db:migrate --migrations-path "${migrationPath}" --url ${url}` to do this i'm using also child_process, and pkg to make and executable.

The problem here is when command runs this throw and error because try to find the package in general node modules or project ones, but i woul like to get it from the executable.

Or, my question, theres a way to execute the function migrate from the package sequelize-cli directly from my project?

Dou you think theres another way to achive this?

**Comment by papb** [comment]
> The problem here is when command runs this throw and error because try to find the package in general node modules or project ones, but i woul like to get it from the executable.

This is probably a mistake by you when configuring/using pkg, read the docs on [pkg's Snapshot Filesystem](https://github.com/zeit/pkg#snapshot-filesystem) carefully, you might have to tweak your paths, I suggest using [fs-jetpack](https://github.com/szwacz/fs-jetpack) for easier manipulation of the filesystem. Also you should use [execa](https://github.com/sindresorhus/execa) instead of `child_process` because it is immensely better.

> Or, my question, theres a way to execute the function migrate from the package sequelize-cli directly from my project?

I don't understand, can you please clarify what you mean?


For now I will close this anyway since I think you are just confused on how to use pkg's snapshot filesystem. We can still talk here though :) Let me know

**Comment by xXLokerXx** [comment]
@papb sorry about the late response, i've a lot of work since those days, i'v already fixed this, i changed the way how it works, for me the solution was creating endpoint and there execute the command, then the folder will be the project one.

And also thanks for taking the time to response me
